CREATE DATABASE IF NOT EXISTS tabungan CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;
USE tabungan;
CREATE TABLE IF NOT EXISTS savings (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  saved_at DATETIME NOT NULL,
  amount BIGINT NOT NULL,
  src VARCHAR(32) NOT NULL,
  raw_text VARCHAR(255) NOT NULL
);
